### ISSUE TITLE
Issue on README

### ISSUE THREAD

**Issue by skeith** [howlCode/tarot_api#1]
README says

> All are prefixed with https://tarot.howlcode.com
> 
> '/cards' Will grab all cards as one object
> 
> '/shuffled' Pulls ALL cards pre-shuffled
> 
> '/random_card' Pulls off one random card
> 
> '/three_cards' Pulls of three random cards
> 
> '/celtic_cross' Grabs 10 random cards

While in reality
`https://tarot.howlcode.com/cards` do work but `https://tarot.howlcode.com/shuffled` or `https://tarot.howlcode.com/three_cards` doesn't work

It was actually `https://tarot.howlcode.com/spreads/shuffled` and `https://tarot.howlcode.com/spreads/three_cards`

**Comment by howlCode** [comment]
Thank you so much! I've fixed the README
