### ISSUE TITLE
Website certificate has possibly expired

### ISSUE THREAD

**Issue by JakeScudder** [howlCode/tarot_api#17]
Not sure if it is an issue on my end, but it looks to me like the web certificate expired august 13th.  This seems to be causing most api requests to fail unless run through certain proxies.

**Comment by howlCode** [comment]
Hey friends! Sorry, things have been nuts lately but I just fixed the SSL issue.

**Comment by lizzSoup** [comment]
Of course! We understand. Thank you for creating and sharing this API, it's
easy to get started with and I appreciate it's existence. I'm excited to be
able to use this project in my portfolio. Keep up the good work.
